### ISSUE TITLE
UUID validation causing fetch to fail in XClarity Service

### ISSUE THREAD

**Issue by EsdrasVP** [lenovo/xclarity_client#111]
There is a UUID handling problem in `lib/xclarity_client/services/xclarity_service.rb#L37`. This piece of code uses a method called `validate` from UUID library, which compares the current ID with a regular expression `[\da-f]{8}-([\da-f]{4}-){3}[\da-f]{12}`. The problem in this approach is that not every ID in the system (i.e. LXCA) follows this exact same format (storage, for instance, uses another one).

We may consider only check if the UUID is `nil` or not. For that, we need to evaluate the impact of this change in the remaining of the XClarity Service code.

**Comment by walteraa** [comment]
@esdrasVP @douglasgabriel is there any pattern in common among the other entities IDs? If positive, it is better creating or own validation method than only check if it is nil, and call it replacing the `UUID.validate`.

Could you guys please check all current entities parsed by our client and after that come back here to discuss again? We can decide together a better approach if there's no pattern.

**Comment by walteraa** [comment]
@esdrasVP @douglasgabriel I was looking at the Xclarity REST API online documentation and I could notice that the UUID in storage is a 16 byte hexadecimal ID it is wrongly named as UUID(once it doesn't follow the UUID pattern) as you guys can se below:

```
 "uri": "storage/208000C0FF280E8B",
   "uuid": "208000C0FF280E8B",
```

Maybe you could check with Lenovo guys if it pattern is being used in all other resources which doesn't follow the UUID pattern and use this information to fix the validation method. Only check if it is `nil` is wrong, using the `blank?` method could be better(once it checks if it is empty string as well), but the better approach is find other common patterns to validate it better.

I believe @rodneyhbrown7 could help you guys out with information about the UUID patterns.

**Comment by walteraa** [comment]
@Sanmoo I agreed with you but we can just check if it is empty(don't check if it is only nil). Despite it will be strange name uuid a variable which doesn't follow UUID canonical form, once name a variable as UUID when it hasn't UUID canonical form sounds very strange, it looks like an issue that will be recurrent considering LXCA REST API.

**Comment by walteraa** [comment]
@EsdrasVP could you please patch this validation as discussed in the comment above?

**Comment by EsdrasVP** [comment]
@Sanmoo @walteraa I agree, for now I'll let only the check for empty UUID in code, as sugested.

**Comment by walteraa** [comment]
Sounds good, @EsdrasVP. Let me know when you do that, so I can merge it.

**Comment by rodneyhbrown7** [comment]
I agree with this approach, actually in miq we only look to assign a 'uid' not required to be a 'uuid'. If lxca is using the value to uniquely identify, we only require that the value is non nil.

**Comment by walteraa** [comment]
I think it is solved. @EsdrasVP I am closing this issue but feel free for reopen it any time you need! 😃
