### ISSUE TITLE
No more maintainers?

### ISSUE THREAD

**Issue by Fryguy** [lenovo/xclarity_client#156]
Apologies for the blast, but it seems the primary maintainers are no longer working on this gem, and it is a critical part of the [ManageIQ](github.com/ManageIQ) project.  Do any of you have admin access to the gem and can give me (@Fryguy) or @agrare commit/admin access?

@abbondanzio, @aminueza, @AndreyMenezes, @caiocmpaes, @CharlleDaniel, @d-m-u, @danielmadruga, @douglasgabriel, @eduardosmoura, @EsdrasVP, @felipedf, @gabrielsvinha, @GustavoDinizMonteiro, @joshuaword2alt, @juliancheal, @kbrock, @light-pedals, @lucashsilva, @maas-ufcg, @ManasaRaoK, @MaysaMacedo, @Newbe-cloud, @odravison, @prabhosa, @rodneyhbrown7, @Sanmoo, @skovic, @terciodemelo, @umrikar, @walteraa, @willliuwx, @yuanjianshi

**Comment by juliancheal** [comment]
Do you mean commit/admin on this repo, or on Rubygems?

**Comment by Fryguy** [comment]
Turns out we have rubygems access which is good ... We need github repo access.

**Comment by prabhosa** [comment]
Lenovo India team is maintainer for this code.

**Comment by agrare** [comment]
Hey @prabhosa are you (or anyone else on your team) available to maintain this gem?
