### ISSUE TITLE
Change repository name

### ISSUE THREAD

**Issue by walteraa** [lenovo/xclarity_client#59]
I was thinking about the possibility of creating LXCA clients in other programming languages. Isn't better change the repository name referencing the language? I mean, something like `xclarity_ruby_client` for ruby, `xclarity_go_client` for golang, and so on...

**Comment by CharlleDaniel** [comment]
I think that  xclarity_ruby_client is a good name and a good idea,  but this is really a issue? 🤔

**Comment by AndreyMenezes** [comment]
I think this not a goal for Lenovo. But I believe we should discuss about this in another moment. Could be interesting.

**Comment by walteraa** [comment]
@CharlleDaniel Yes, it is! Any project change(including repository name change) can be considered an Issue. From a bug fix request to a new feature, even a design proposal can be considered an issue. :smile:

**Comment by walteraa** [comment]
Why not @AndreyMenezes? A Cloud manager or SysAdmin could use a possible Python LXCA client to create provision scripts over a LXCA environment, for example. It can be very useful!

**Comment by douglasgabriel** [comment]
Once we have a repo called [pylxca](https://github.com/lenovo/pylxca) I think that would be good to standardize the libs name and I think that the @walteraa suggestion (xclarity_< lang >_client) is a good pattern :+1: . Also, an standardized interface (at code level) should be adopt, but I think that this could be discussed in another issue :smile:

**Comment by caiocmpaes** [comment]
I liked @walteraa suggestion too. The example with the [pylxca](https://github.com/lenovo/pylxca) is a perfect case of this issue.

**Comment by rodneyhbrown7** [comment]
What would be the impact of changing this library to xclarity_ruby_client or  rubylxca?  I guess the only known user of this library is the puppet code and the manageiq code.

**Comment by walteraa** [comment]
The only impact I see is that will be necessary update the `Gemfile` to change the reference to this client. It is important that the project name in rubygems should be updated as well.

**Comment by rodneyhbrown7** [comment]
One thought.  If we update the name of the repository but leave the name of the gem the same, would that be good enough?  The fact that it is a gem file should be enough to identify it as a ruby component (i.e. xclarity_client.gem is by default a ruby module).

**Comment by walteraa** [comment]
It would be different than the usual(normally the gems follow its repository names) but it sounds good for me.

**Comment by navalkp** [comment]
chef.lenovo-lxca also use this.
